### ISSUE TITLE
[BUG] Incorrect Textures on VAL15

### ISSUE THREAD

**Issue by Popsoap** [Mythotic-Tinker-Station/lexicon#20]
**Type of bug**
texture error

**Mapset name**
Valiant

**Map name**
VAL15

**Describe the bug**
Slimefall texture replacing metal grating and switch texture on VAL15.

**Screenshots**
*Current textures*
![LexiconTextureIssue1VAL15](https://user-images.githubusercontent.com/8683430/69891404-f8c6fd00-12c1-11ea-8e1e-039b88c701db.png)
![LexiconTextureIssue2VAL15](https://user-images.githubusercontent.com/8683430/69891405-f8c6fd00-12c1-11ea-91a7-be65ad253944.png)

*Intended textures*
![TextureIssue1VAL15](https://user-images.githubusercontent.com/8683430/69891438-1b591600-12c2-11ea-89cc-c0d7cf7a898d.png)
![TextureIssue2VAL15](https://user-images.githubusercontent.com/8683430/69891439-1b591600-12c2-11ea-8256-33627805807b.png)

**Comment by Tribeam** [comment]
Fixed in 1175c25
