### ISSUE TITLE
[Suggestion] Update Mapset: Doom Core Trilogy

### ISSUE THREAD

**Issue by michael-is-qcde** [Mythotic-Tinker-Station/lexicon#23]
**Type of MapSet**
Normal

**Mapset Name**
Doom Core Trilogy

**How many maps**
77

**Custom content**
Music, graphics

**Does this run on doom2 or a different IWAD**
Yes

**Author**
Michael Jan Krizik (valkiriforce)

**Download Link**
https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/dctrilogy

**Comment by svcino** [comment]
after selected Doom Core Trilogy you can be either DC01 start or DC33 start or DC65 start 
with selection DC00 map
