### ISSUE TITLE
[Suggestion] Add Mapset: Alienated

### ISSUE THREAD

**Issue by michael-is-qcde** [Mythotic-Tinker-Station/lexicon#24]
**Type of MapSet**
Normal

**Mapset Name**
Alienated

**How many maps**
10

**Custom content**
Music, Ancient Aliens graphics

**Does this run on doom2 or a different IWAD**
Yes

**Author**
Michal ''Lorenzo'' Kurowski

**Download Link**
https://www.doomworld.com/idgames/levels/doom2/Ports/a-c/alienated

**Comment by mifu666** [comment]
Moving to new ticket system. Mapset suggestions should now be raised on discord.
