### ISSUE TITLE
[BUG] GD24 uses a trick to simulate a 3d floor, this doesnt translate well in coop.

### ISSUE THREAD

**Issue by Tribeam** [Mythotic-Tinker-Station/lexicon#25]
**Type of bug**
Single Player Mapping Trick

**Mapset name**
Going Down

**Map name**
GD24

**Describe the bug**
There is a bridge in this map, that instantly raises and lowers when players are near windows, this works fine from a player's window prespective, but other players that are on the bridge will see the bridge's floor drop/raise when other players go to the windows.

**Expected behavior**
3D Floor

**Screenshots**
Screeshot taken from a livestream:
![goingdownoops](https://user-images.githubusercontent.com/57662310/70295243-e78f5c00-17ab-11ea-8e41-0efb8aea8b7b.png)

This is intended behavior of this map, but it doesnt do well in coop, we have a policy that we dont mess with the original maps unless we really have to...this would be a major change for this map and we might need to get the author's permission to do so.

**Comment by svcino** [comment]
also on GD29 is do not have RED spider mastermind and cause never exit GD29 
in MP you need vote to GD30

**Comment by svcino** [comment]
SPMT

**Comment by mifu666** [comment]
> also on GD29 is do not have RED spider mastermind and cause never exit GD29
> in MP you need vote to GD30

This should be raised in another issue if you do not mind, please.
