### ISSUE TITLE
[BUG] Hanging corpses in EP207 replacing cells

### ISSUE THREAD

**Issue by Popsoap** [Mythotic-Tinker-Station/lexicon#28]
**Type of bug**
gamebreaking

**Mapset name**
Epic 2

**Map name**
EP207 (and possibly more)

**Describe the bug**
EP207 has hanging corpses which replace the cell pickups normally found.

**Expected behavior**
Hanging corpses are replaced with cells

**Screenshots**
![BlockingCorpses](https://user-images.githubusercontent.com/8683430/71537000-8a368880-28db-11ea-9fdd-b056e2c018d0.png)
![SkyCorpses](https://user-images.githubusercontent.com/8683430/71537001-8a368880-28db-11ea-9fc3-f9d2f44fe83d.png)

**Comment by Tribeam** [comment]
Fixed in 9a14e2b.
