### ISSUE TITLE
[BUG] Deus Vult II using Scythe 2 Afrits

### ISSUE THREAD

**Issue by Popsoap** [Mythotic-Tinker-Station/lexicon#29]
**Type of bug**
gamebreaking

**Mapset name**
Deus Vult II

**Describe the bug**
Deus Vult II currently uses the same Afrits found in Scythe 2. The Scythe 2 Afrits are much sturdier (2500 hp) than the ones found in Deus Vult II (1500 hp).

**Expected behavior**
Deus Vult II uses Afrits with 1500 hp.

**Comment by svcino** [comment]
need Afrits to rename to SCAfrits to avoid conflicts of complex CCF 
and afrits to rename to DV2Afrits

**Comment by Tribeam** [comment]
Fixed in 36c642e
