### ISSUE TITLE
[BUG] Unknown texture: "EP2SKY2"

### ISSUE THREAD

**Issue by Popsoap** [Mythotic-Tinker-Station/lexicon#30]
**Type of bug**
texture error

**Mapset name**
Epic 2

**Map name**
EP212 - EP220

**Describe the bug**
The second sky from Epic 2 is missing.

**Screenshots**
![EP218Sky](https://user-images.githubusercontent.com/8683430/72192475-828edd80-33cb-11ea-92a3-01c611e8a5ae.png)

**Comment by Tribeam** [comment]
Fixed in b78ac66
