### ISSUE TITLE
[BUG] Community Chest 2 missing music

### ISSUE THREAD

**Issue by Popsoap** [Mythotic-Tinker-Station/lexicon#32]
**Type of bug**
gamebreaking

**Mapset name**
Community Chest 2

**Map name**
CC202, CC203 and intermissions for Community Chest 2

**Describe the bug**
Missing music for CC202, CC203, and Community Chest 2 intermissions

**Comment by Tribeam** [comment]
Fixed in 28229dc and e3cd1cd
