### ISSUE TITLE
[BUG] BTS-X textures misapplied

### ISSUE THREAD

**Issue by michael-is-qcde** [Mythotic-Tinker-Station/lexicon#34]
**Type of bug**
Texture error

**Mapset name**
BTS-X

**Map name**
BX120, BX121, BX123

**Describe the bug**
BX120: Exit room has a bloodfall with one frame of ventilation 
https://cdn.discordapp.com/attachments/456775799731781634/657460633910116353/unknown.png 
https://cdn.discordapp.com/attachments/456775799731781634/657460664603770910/unknown.png
https://cdn.discordapp.com/attachments/456775799731781634/657460709801852949/unknown.png
BX121: in the first room, animated propellers are tiled in a way that makes me doubt is intended by mapper. Fan blades don't bend like that
https://cdn.discordapp.com/attachments/456775799731781634/657461524578697226/unknown.png
BX123: missing waterfall textures
https://cdn.discordapp.com/attachments/456775799731781634/657463180892700673/unknown.png

**Additional context**
Please take a look at all of the BTS-X maps, a few errors on a few maps means it's likely there are more in the same mapset.

**Comment by Tribeam** [comment]
BX120: Fixed in 2b4b288
BX121: Fixed in d66fd32; This wasnt suppose to be a fan at all, but a grate texture
BX123: Fixed in 3285fa7
