### ISSUE TITLE
[BUG] GD29 Do not have Dehacked SS for red spider mastermind, and cannot beat GD29

### ISSUE THREAD

**Issue by svcino** [Mythotic-Tinker-Station/lexicon#35]
**Type of bug**
gamebreaking

**Mapset name**
Going Down

**Map name**
GD29

**Expected behavior**
GD29 do not have red spider mastermind, and cause to cannot finish GD29

**Screenshots**

![Screenshot_Doom_20200120_121519](https://user-images.githubusercontent.com/33147204/72698583-c5954180-3b7f-11ea-952b-79d2a60e5360.png)

**idmypos Coords**
X: -2570
Y: 288
Z: 0

**Additional context**

**Comment by Tribeam** [comment]
Fixed in c6c7dbb

**Comment by svcino** [comment]
yeah
