### ISSUE TITLE
[Suggestion] Add Mapset: 1 Monster Megawad

### ISSUE THREAD

**Issue by mattbratt11** [Mythotic-Tinker-Station/lexicon#36]
**Type of MapSet**
Normal

**Mapset Name**
One Monster Megawad

**How many maps**
25

**Custom content**
Textures, Graphics, and Music

**Does this run on doom2 or a different IWAD**
Doom 2: Yes
Other: No

**Author**
Various (Doomworld Community)

**Download Link**
https://www.doomworld.com/idgames/levels/doom2/megawads/1monster

**Comment by svcino** [comment]
Doomworld Community or DWC for short

**Comment by mifu666** [comment]
Moving to new ticket system. Mapset suggestions should now be raised on discord.
