### ISSUE TITLE
[BUG] Missing texture on EP104 and EP105

### ISSUE THREAD

**Issue by Popsoap** [Mythotic-Tinker-Station/lexicon#39]
**Type of bug**
texture error

**Mapset name**
Epic 1

**Map name**
EP104, EP105

**Screenshots**
![Screenshot_Doom_20200122_123246](https://user-images.githubusercontent.com/8683430/72922796-58b2b080-3d13-11ea-866c-0e099facdbb2.png)

**Comment by Tribeam** [comment]
Fixed in f04c5b1
