### ISSUE TITLE
Valiant - broken lift in the pit

### ISSUE THREAD

**Issue by Mech-cyber** [Mythotic-Tinker-Station/lexicon#48]
**Type of bug**
Gamebreaking

**Mapset name**
Valiant

**Map name**
VAL10

**Describe the bug**
The lift on which Cyberdemon appears just stays where it is after the fight and never rises(as shown in the screenshot)
![Screenshot_Doom_20200129_000459](https://user-images.githubusercontent.com/59827086/73290868-b3776b00-4231-11ea-889f-216622e90519.png)
![Screenshot_Doom_20200129_000702](https://user-images.githubusercontent.com/59827086/73290869-b4100180-4231-11ea-8adc-e7a12c5c5eda.png)

.

**Expected behavior**
Cyberdemon's death must unlock the lift, so it can go up and down freely.

**To Reproduce (if Game Breaking)**
1. Go to the yellow key and try to pick it
2. In the two pits section, go to the right one
3. Kill appeared Cyberdemon
4. Get stuck there forever!

**idmypos Coords**
X: 7350
Y: -3507
Z: -248

**Additional context**
I played with High Noon Drifter mod.

**Comment by Tribeam** [comment]
Fixed in e25c054
