### ISSUE TITLE
[BUG] Back to Saturn X map numbers are off by one...

### ISSUE THREAD

**Issue by Tribeam** [Mythotic-Tinker-Station/lexicon#49]
**Type of bug**
Not Right

**Mapset name**
Back to Saturn X

**Map name**
IDK yet

**Describe the bug**
A lot of maps are off by one in map number

**Expected behavior**
To not be off by one in map number

**Comment by svcino** [comment]
WRONG!

**Comment by Tribeam** [comment]
Well, idk if there is a missing map, but I can confirm that the map numbers of lexicon and btsx are off by one, not sure why that is but it might be a concern, so i'll leave this up until we find more info about this...

**Comment by Popsoap** [comment]
It looks like [this map](https://doomwiki.org/wiki/MAP31:_Optical_Hopscotch_(BTSX-E1)) is missing. The [map that is currently there](https://doomwiki.org/wiki/MAP32:_The_Hard_Way_(BTSX-E1)) was moved to MAP32.

**Comment by mifu666** [comment]
This is now fixed in the rebuild branch
