### ISSUE TITLE
[BUG] Slimefall texture on VAL13

### ISSUE THREAD

**Issue by Popsoap** [Mythotic-Tinker-Station/lexicon#50]
**Type of bug**
texture error

**Mapset name**
Valiant

**Map name**
VAL13

**Describe the bug**
Slimefall texture replacing red marble texture on VAL13

**Screenshots**
*Current texture*
![VAL13SlimeTexture](https://user-images.githubusercontent.com/8683430/74587858-4861be80-4fbd-11ea-8bba-10cb2ba18fcc.png)
*Intended texture*
![VAL13CorrectTexture](https://user-images.githubusercontent.com/8683430/74587991-6976df00-4fbe-11ea-8cfa-a1ebe1b6871b.png)

**Comment by Tribeam** [comment]
Fixed in 5513b94
