### ISSUE TITLE
[BUG] Incorrect lava and teleport texture on EP209

### ISSUE THREAD

**Issue by Popsoap** [Mythotic-Tinker-Station/lexicon#51]
**Type of bug**
texture error

**Mapset name**
Epic 2

**Map name**
EP209

**Describe the bug**
Standard muddy water texture in place of lava texture from Epic 2

**Screenshots**
*Current texture*
![Epic2Mud](https://user-images.githubusercontent.com/8683430/74591269-23c90f00-4fdc-11ea-9bd1-080b1b864885.png)
![Epic2MudTeleport](https://user-images.githubusercontent.com/8683430/74591555-81f6f180-4fde-11ea-95f9-2e239a1a4a61.png)

*Intended texture*
![Epic2Lava](https://user-images.githubusercontent.com/8683430/74591276-2deb0d80-4fdc-11ea-99d5-f9090dd6a1a4.png)
![Epic2Teleport](https://user-images.githubusercontent.com/8683430/74591558-84f1e200-4fde-11ea-8ad1-295bdc71324c.png)

**Comment by Tribeam** [comment]
Fixed in 68e8eb1
