### ISSUE TITLE
[REBUILD] 1994 Tune up Project Requires Testing!!!

### ISSUE THREAD

**Issue by mifu666** [Mythotic-Tinker-Station/lexicon#61]
1994 Tune up Project was just re-added to the rebuild branch. This requires testing from the crack team of mapset testers.

Please add a note to the ticket if you are testing this and please report back on the following:

* Any texture issues (missing or incorrect textures etc)
* Thing issues (incorrect decorations. monsters etc
* Show stopping bugs
* Any other issues

This should be tested within the week before the weekend with the other mapsets added.

**Comment by Fookerton** [comment]
on map 94TU07, the final door is failing to trigger, rendering the map unable to be completed. Pretty sure this is a bug in the base mapset and zandronum though.

**Comment by Fookerton** [comment]
the second intermission screen (ENTERING...) is missing a texture 
![Screenshot_Doom_20200419_090223](https://user-images.githubusercontent.com/63958913/79689939-eaa05b80-8225-11ea-8fee-ae324f0c708a.png)

**Comment by mifu666** [comment]
Map07 is still broken. Will keep this pinned until it is fixed. missing entering texture is however fixed.

_Dev note: Fixed in commit 7529b52_

**Comment by Tribeam** [comment]
Map07 problem fixed in commit _7529b52_
