### ISSUE TITLE
[Suggestion] Add Mapset: Gridlock

### ISSUE THREAD

**Issue by Tribeam** [Mythotic-Tinker-Station/lexicon#76]
Suggested by haruko haruhara on discord

**Type of MapSet**
Normal

**Mapset Name**
Gridlock

**How many maps**
32

**Custom content**
Graphics, Dehacked

**Does this run on doom2 or a different IWAD**
Doom2

**Authors**
Various 

**Download Link**
https://www.doomworld.com/forum/topic/85553-released-gridlock-a-community-project-maps-aligned-to-the-64-units-grid/

**Comment by Zelaven** [comment]
asd
