### ISSUE TITLE
[BUG] Afrits missing in Scythe 2 maps

### ISSUE THREAD

**Issue by Popsoap** [Mythotic-Tinker-Station/lexicon#8]
**Type of bug**
gamebreaking

**Mapset name**
Scythe 2

**Map name**
SC225 - SC230

**Describe the bug**
Commander Keens are not replaced by Afrits on Scythe 2 maps.

**Expected behavior**
Replacer should spawn Afrits in Commander Keen spots on SC2XX maps.

**Screenshots**
![MisplacedCommanderKeen](https://user-images.githubusercontent.com/8683430/68996845-36a93780-0865-11ea-8cc0-ef6f53d36ce9.png)

**idmypos Coords**
This was done on SC226
x: 173
y: 547
z: 40

**Comment by Tribeam** [comment]
Fixed in edfa697
