### ISSUE TITLE
[REBUILD] Speed of Doom needs testing!!!

### ISSUE THREAD

**Issue by michael-is-qcde** [Mythotic-Tinker-Station/lexicon#80]
Speed of Doom was just re-added to the rebuild branch. This requires testing from the crack team of mapset testers.

Please add a note to the ticket if you are testing this and please report back on the following:

    Any texture issues (missing or incorrect textures etc)
    Thing issues (incorrect decorations. monsters etc)
    Show stopping bugs
    Any other issues

This should be tested within the week before other mapsets are added.

_Please note that the HUB map is currently being rebuilt and is not available right now, use_ `changemap SOD_01` _to start the mapset_

**Comment by michael-is-qcde** [comment]
SOD_05: This transparent texture on a railing is non-transparent from some angles but transparent from others. I have not the slightest idea.
![image](https://user-images.githubusercontent.com/57696110/81501093-9ce8b180-9300-11ea-8a7b-daf02908561f.png)

_Dev note: Fixed in commit 43d2c2a_

**Comment by Tribeam** [comment]
43d2c2a fixes the texture rendering error, turns out the lib used by the extractor likes to optimize PNGs, this particular texture has all gray colors so it decided to save it as a grayscale image, zandronum apparently does not like that, so changing the image to an indexed PNG fixed this issue.

**Comment by michael-is-qcde** [comment]
SOD_29: Like in original sodfinal.wad, these bricks flicker aggressively, like there are two surfaces with different textures occupying the same space. Maybe we could fix it for Lexicon?
![image](https://user-images.githubusercontent.com/57696110/81508191-f2d34e80-932c-11ea-8870-4729cb79a4e2.png)

_Dev note: Fixed in commit b5b8704_

**Comment by Tribeam** [comment]
Fixed what looks like a copy/paste job gone wrong causing overlapping lines in commit b5b8704

**Comment by michael-is-qcde** [comment]
Speed of Doom is completable and the issues I reported were resolved.
