### ISSUE TITLE
[REBUILD] Unholy Realms needs testing!!!

### ISSUE THREAD

**Issue by Tribeam** [Mythotic-Tinker-Station/lexicon#85]
Unholy Realms was just re-added to the rebuild branch. This requires testing from the crack team of mapset testers.

Please add a note to the ticket if you are testing this and please report back on the following:

Any texture issues (missing or incorrect textures etc)
Thing issues (incorrect decorations, monsters etc)
Show stopping bugs
Any other issues

This should be tested within the week before other mapsets are added.

Please note that the HUB map is currently being rebuilt and is not available right now, use changemap UHLY01 to start the mapset

**Comment by michael-is-qcde** [comment]
UR__11: Can't be finished. Exit remains blocked by the door with tag 666.
Unholy Realms modified Cyberdemon to call A_KeenDie in its death sequence, which opens the doors tagged 666.

**Comment by michael-is-qcde** [comment]
Previous issue fixed by "Fixed UR__11 exit doors not triggering when cyberdemon is killed."

Proceeding with testing the rest of the mapset.

**Comment by michael-is-qcde** [comment]
Unholy Realms is completable and the issues I reported were resolved.
