### ISSUE TITLE
[Suggestion] Add Mapset: The Alfonzone

### ISSUE THREAD

**Issue by Lugawi** [Mythotic-Tinker-Station/lexicon#89]
**Type of MapSet**
Normal

**Mapset Name**
The Alfonzone

**How many maps**
62

**Custom content**
Textures, Graphics, and Music

**Does this run on doom2 or a different IWAD**
Doom 2: Yes
Other: No

**Author**
Pinchy

**Download Link**
https://forum.zdoom.org/viewtopic.php?t=58501
https://drive.google.com/open?id=1psTMIQ2ebXnGYABMdcLn05OUbpuQG0GD

**Comment by mifu666** [comment]
Moving to new ticket system. Mapset suggestions should now be raised on discord.
