### ISSUE TITLE
[Suggestion] Feature Request: Support for Doom Complete iwad (WadSmoosh)

### ISSUE THREAD

**Issue by mifu666** [Mythotic-Tinker-Station/lexicon#9]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Theres a iwad that people can create using wadsmoosh to merge all the iwads (doom, doom2, final doom etc) into one big iwad. Lexicon should support voting to those mapsets. A check via ACS is required however to determine which iwads are available.

**Describe alternatives you've considered**
N/A (Was pre discussed on discord)

**Additional context**
Doom complete is now playable on zandronum due to a few changes i made to the wadsmoosh tool, people may want to host lexicon with doom complete support

**Comment by Tribeam** [comment]
List of things todo for this

- [x] Check for iwads
- [x] Make Title Screens
- [x] Add each iwad/episode to the acs list
- [x] Add screens to map
- [ ] Add map names and credits to the language.txt
- [ ] Find out how to cosmetically tell users that an iwad screen is unsuable
- [ ] Modify TitleMake to allow for subtext
- [ ] Compare user's iwad to the server's
- [ ] Make new textures for the back of screens
- [ ] Change the color of the iwad screens
- [x] Mifu owes me a dollar for all this work

**Comment by mifu666** [comment]
404 dollar not found

**Comment by Tribeam** [comment]
This feature is postponed until a major release is set.
