### ISSUE TITLE
[BUG] LOADACS files are missing "#library", causing conflicts and bizarre glitches when played with other mods

### ISSUE THREAD

**Issue by InageMantra** [Mythotic-Tinker-Station/lexicon#90]
![Untitled3](https://user-images.githubusercontent.com/73678334/97652365-924be100-1a34-11eb-9eca-b3ead379f28b.png)
![Untitled2](https://user-images.githubusercontent.com/73678334/97652377-9677fe80-1a34-11eb-8c94-ddd07744d9c8.png)
![Untitled](https://user-images.githubusercontent.com/73678334/97652382-9841c200-1a34-11eb-9ed7-2646916ded68.png)

**Comment by InageMantra** [comment]
In addition to seemingly overflowed HudMessages, sometimes a map will just randomly end during gameplay. I suspect that, specifically, has something to do with the script seen in the above screenshot.

Any gameplay mod that uses its own global ACS scripts has the potential to cause conflicts. You can replicate my screenshot by running Lexicon with "sd64_unofficial_v20a.pk3" by SamuZero15. That pk3 contains properly library'd scripts and causes no conflicts with any other mods from what I've observed.

-- Aenima

**Comment by mifu666** [comment]
Closing as issue moved to https://bugtracker.mythotic.com/view.php?id=4
