### ISSUE TITLE
[BUG] Maps with more than ≈3000 monsters

### ISSUE THREAD

**Issue by MrSatan6666** [Mythotic-Tinker-Station/lexicon#91]
**Type of bug**
Game Breaking

**Mapset name**
Sunder

**Map name**
SND11, SND12, SND15 && SND16

**Describe the bug**
Maps with more than ≈3000 monsters that don't the SOUNDBLOCK linedef will cause excessive lag when monsters are alerted.
Playing these maps in multiplayer with more than one client in game and alerting monsters will soft lock server.
This was tested with only Lexicon-beta-build-133.pk3 && Lexicon-miscdata-beta-build-133.pk3 loaded.

**Expected behavior**
Server is soft locked until all clients leave server, map is changed, or monsters are killed.

**To Reproduce (if Game Breaking)**
1. Start server.
2. Connect 2 or more clients and join game.
3. Changemap to one of those maps.
4. Alert monsters.

**Additional context**
Other map packs that have maps that have more than ≈3000 monsters and don't use the SOUNDBLOCK linedef will have this problem.

**Comment by mifu666** [comment]
Closing as issue has been transfered over to our offical bug tracker at https://bugtracker.mythotic.com/view.php?id=3
