### ISSUE TITLE
[BUG] Jenkins web disappeared

### ISSUE THREAD

**Issue by mattbratt11** [Mythotic-Tinker-Station/lexicon#92]
The Jenkins Website somehow got an Unexpected Error upon trying to visit.
Is there a way to upload Lexicon's New Build on TSPG anytime soon?

**Comment by mifu666** [comment]
Hello. This is not a bug at all but I can address this here (hence the invalid lable)

For more context however, Jenkins was hosted on the TSPG server box. It was using up a ton of resources so it was later shut down.

I will be hosting the Jenkins instance elsewhere when the time comes. As for a new version the current version is what is uploaded already on TSPG. There is no new build currently as we have been rebuilding the project from the ground up.

As for an ETA? Soon. Could use more people to help with the building process however to speed things up though!
