### ISSUE TITLE
[Suggestion] Add Mapset: <No chance>

### ISSUE THREAD

**Issue by blueslight** [Mythotic-Tinker-Station/lexicon#93]
type:Slaughter

name:no chance

maps: 1

Custon content:textures,graphics and music

Does this run on doom2?
Yes

in others:no

author:Death-Destiny

Download Link:
https://www.doomworld.com/idgames/levels/doom2/m-o/nochance

**Comment by mifu666** [comment]
Moving to new ticket system. Mapset suggestions should now be raised on discord.
