### ISSUE TITLE
[Suggestion] Add Mapset: SIGIL

### ISSUE THREAD

**Issue by PolarManne** [Mythotic-Tinker-Station/lexicon#99]
**Type of MapSet**
Normal

**Mapset Name**
SIGIL

**How many maps**
9

**Custom content**
A small amount of new textures, nothing replaced.

**Does this run on doom2 or a different IWAD**
DOOM.WAD

**Author**
John Romero

**Download Link**
https://www.doomworld.com/idgames/levels/doom/Ports/s-u/sigil_v1_21

**Comment by mifu666** [comment]
Moving to new ticket system. Mapset suggestions should now be raised on discord.
